# AI Cash Revolution - Promtail Configuration
# Log collection and forwarding to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # AI Cash Revolution API Server Logs
  - job_name: aicash-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: aicash-api
          service: api-server
          environment: production
          __path__: /var/log/app/api/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            requestId: requestId
            userId: userId
            method: method
            url: url
            statusCode: statusCode
            responseTime: responseTime

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          service:
          method:
          statusCode:

      - output:
          source: message

  # Nginx Access Logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          service: nginx
          log_type: access
          __path__: /var/log/nginx/access.log

    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<url>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" "(?P<http_x_forwarded_for>[^"]*)" rt=(?P<request_time>\S+) uct="(?P<upstream_connect_time>\S+)" uht="(?P<upstream_header_time>\S+)" urt="(?P<upstream_response_time>\S+)"'

      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700

      - labels:
          method:
          status:
          remote_addr:

  # Nginx Error Logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          service: nginx
          log_type: error
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): (?P<message>.*)'

      - timestamp:
          source: timestamp
          format: 2006/01/02 15:04:05

      - labels:
          level:
          pid:

  # PostgreSQL Logs
  - job_name: postgresql
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgresql
          service: database
          __path__: /var/log/postgresql/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \w{3}) \[(?P<pid>\d+)\] (?P<level>\w+): (?P<message>.*)'

      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000 MST

      - labels:
          level:
          pid:

  # Redis Logs
  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          service: cache
          __path__: /var/log/redis/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<pid>\d+):(?P<role>\w) (?P<timestamp>\d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2}\.\d{3}) (?P<level>.) (?P<message>.*)'

      - timestamp:
          source: timestamp
          format: 02 Jan 2006 15:04:05.000

      - labels:
          level:
          role:
          pid:

  # Docker Container Logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.+)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

    pipeline_stages:
      - cri: {}
      - json:
          expressions:
            timestamp: time
            message: log
            level: level
            service: service

      - timestamp:
          source: timestamp
          format: RFC3339Nano

      - labels:
          service:
          level:
          container_name:

  # System Logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          service: system
          __path__: /var/log/syslog

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2}) (?P<hostname>\S+) (?P<service>\S+): (?P<message>.*)'

      - timestamp:
          source: timestamp
          format: Jan _2 15:04:05

      - labels:
          hostname:
          service:

  # Trading System Specific Logs
  - job_name: trading-signals
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading-signals
          service: trading-engine
          component: signal-generation
          __path__: /var/log/app/trading/signals/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            instrument: instrument
            signal_type: signal_type
            confidence: confidence
            direction: direction
            entry_price: entry_price
            stop_loss: stop_loss
            take_profit: take_profit
            message: message

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          instrument:
          signal_type:
          direction:

  # ML/AI Training Logs
  - job_name: ml-training
    static_configs:
      - targets:
          - localhost
        labels:
          job: ml-training
          service: ml-engine
          component: training
          __path__: /var/log/app/ml/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            model: model
            accuracy: accuracy
            loss: loss
            epoch: epoch
            message: message

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          model:

  # Audit Logs
  - job_name: audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit
          service: audit
          __path__: /var/log/app/audit/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            user_id: user_id
            action: action
            resource: resource
            ip_address: ip_address
            user_agent: user_agent
            result: result

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          action:
          resource:
          result: