# AI Cash Revolution - Prometheus Configuration
# Comprehensive monitoring setup for production infrastructure

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aicash-revolution-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # AI Cash Revolution API Server
  - job_name: 'aicash-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node.js Application Metrics
  - job_name: 'aicash-app-metrics'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/metrics/detailed'
    scrape_interval: 30s

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis Cache Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # SSL Certificate Monitoring
  - job_name: 'ssl-exporter'
    static_configs:
      - targets: ['ssl-exporter:9219']
    scrape_interval: 300s

  # Blackbox Exporter (External Monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://aicash-revolution.com
        - https://aicash-revolution.com/api/health
        - https://aicash-revolution.com/api/auth/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Trading System Specific Metrics
  - job_name: 'trading-signals'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/metrics/trading'
    scrape_interval: 5s
    honor_labels: true

  # ML/AI Performance Metrics
  - job_name: 'ml-metrics'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/metrics/ml'
    scrape_interval: 60s

  # External API Monitoring
  - job_name: 'external-apis'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api-fxtrade.oanda.com/v3/accounts
        - https://www.cmegroup.com/market-data
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"