[phases.setup]
aptPkgs = ['python3-dev', 'build-essential', 'python3-setuptools', 'gcc', 'g++']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/python -m pip install --upgrade pip',
  '/opt/venv/bin/python -m pip install --upgrade setuptools wheel',
  '/opt/venv/bin/python -m pip install -r requirements.txt'
]

[start]
cmd = '/opt/venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT'
